import type { BlogPost } from "./content";

const author = {
  en: {
    name: "Dr. Ali Alheneiti Editorial Team",
    title: "Cosmetic Dentistry · Amman, Jordan",
    bio: "Reviewed for patient clarity by a cosmetic dentistry team focused on natural veneers, Hollywood Smile planning, implants, and premium treatment journeys."
  },
  ar: {
    name: "الفريق التحريري للدكتور علي الحنيطي",
    title: "طب تجميل الأسنان · عمّان، الأردن",
    bio: "محتوى مُراجع لراحة المريض ووضوح القرار، مع تركيز على الفينير الطبيعي، تصميم الابتسامة، زراعة الأسنان، وتجربة علاج راقية."
  }
} satisfies BlogPost["author"];

const consultationCta = {
  en: "Not sure which treatment fits your case? Share your smile photos privately on WhatsApp and our team will guide the next step.",
  ar: "لست متأكداً ما العلاج المناسب لحالتك؟ شارك صور ابتسامتك عبر واتساب بخصوصية وسيقوم الفريق بإرشادك للخطوة التالية."
};

export const seoBlogPosts: BlogPost[] = [
  {
    slug: "hollywood-smile-in-jordan-cost-process-natural-results",
    relatedService: "dental-veneers-jordan",
    title: { en: "Hollywood Smile in Jordan: Cost, Process, Types, and Natural Results", ar: "ابتسامة هوليود في الأردن: السعر، الخطوات، الأنواع، والنتائج الطبيعية" },
    seoTitle: { en: "Hollywood Smile in Jordan: Cost & Natural Results", ar: "ابتسامة هوليود في الأردن: السعر والنتائج الطبيعية" },
    metaDescription: { en: "Guide to Hollywood Smile in Jordan: cost factors, veneers, whitening, implants, timeline, natural design, and consultation planning.", ar: "دليل ابتسامة هوليود في الأردن: عوامل السعر، الفينير، التبييض، الزراعة، المدة، النتيجة الطبيعية والاستشارة." },
    h1: { en: "Hollywood Smile in Jordan: Cost, Process, Types, and Natural Results", ar: "ابتسامة هوليود في الأردن: السعر، الخطوات، الأنواع، والنتائج الطبيعية" },
    excerpt: { en: "A clear patient guide to Hollywood Smile in Jordan, including cost factors, treatment options, natural design, GCC timelines, and common mistakes to avoid.", ar: "دليل واضح لابتسامة هوليود في الأردن يشمل عوامل السعر، الخيارات العلاجية، التصميم الطبيعي، مدة مرضى الخليج، والأخطاء الشائعة." },
    category: { en: "Hollywood Smile", ar: "ابتسامة هوليود" },
    readTime: "11 min read",
    coverImage: {
      en: "/media/hollywood-smile-in-jordan-cost-process-natural-results.webp",
      ar: "/media/hollywood-smile-in-jordan-cost-process-natural-results-arabic.webp"
    },
    coverAlt: { en: "Natural Hollywood Smile veneers result in Jordan", ar: "نتيجة ابتسامة هوليود طبيعية بالفينير في الأردن" },
    keywords: ["Hollywood Smile in Jordan", "Hollywood Smile cost Jordan", "Hollywood Smile Amman", "Hollywood Smile veneers", "natural Hollywood Smile", "Hollywood Smile for GCC patients", "ابتسامة هوليود في الأردن", "سعر ابتسامة هوليود في الأردن", "هوليود سمايل في عمان"],
    lastUpdated: "2026-07-06",
    author,
    quickAnswer: {
      en: ["A Hollywood Smile is not one fixed package. It is a smile design plan that may include veneers, whitening, crowns, implants, gum contouring, orthodontics, or a combination.", "Cost in Jordan depends on the number of teeth, material, gum and bite condition, old restorations, imaging, lab work, and whether the patient needs staged visits."],
      ar: ["ابتسامة هوليود ليست باقة واحدة ثابتة، بل خطة تصميم ابتسامة قد تشمل الفينير، التبييض، التيجان، الزراعة، تعديل اللثة، التقويم أو الدمج بينها.", "يعتمد السعر في الأردن على عدد الأسنان، نوع المادة، حالة اللثة والعضة، التركيبات القديمة، التصوير، المختبر، وهل تحتاج الحالة إلى مراحل متعددة."]
    },
    ctaText: {
      en: "Share your smile photos privately on WhatsApp for clear guidance on suitable options and next steps.",
      ar: "شارك صور ابتسامتك عبر واتساب بخصوصية، وسيقوم الفريق بإرشادك إلى الخيارات المناسبة والخطوة التالية."
    },
    internalLinks: [
      { href: "/services/dental-veneers-jordan", label: { en: "Dental Veneers in Jordan", ar: "فينير الأسنان في الأردن" }, description: { en: "Natural veneer planning for smile design cases.", ar: "تخطيط فينير طبيعي لحالات تصميم الابتسامة." } },
      { href: "/services/teeth-whitening-amman", label: { en: "Teeth Whitening in Amman", ar: "تبييض الأسنان في عمّان" }, description: { en: "A conservative option when color is the main concern.", ar: "خيار محافظ عندما يكون اللون هو المشكلة الأساسية." } },
      { href: "/services/dental-implants-amman", label: { en: "Dental Implants in Amman", ar: "زراعة الأسنان في عمّان" }, description: { en: "For missing teeth inside a full smile plan.", ar: "للأسنان المفقودة ضمن خطة ابتسامة كاملة." } },
      { href: "/contact", label: { en: "Book Your Consultation", ar: "احجز استشارتك" }, description: { en: "Share photos before booking your visit to Amman.", ar: "شارك صورك قبل حجز زيارتك إلى عمّان." } }
    ],
    suggestedImages: [
      { fileName: "hollywood-smile-jordan-natural-veneers.webp", alt: { en: "Natural Hollywood Smile veneers in Jordan", ar: "ابتسامة هوليود طبيعية بالفينير في الأردن" } },
      { fileName: "hollywood-smile-amman-smile-design-consultation.webp", alt: { en: "Smile design consultation for Hollywood Smile in Amman", ar: "استشارة تصميم ابتسامة هوليود في عمّان" } }
    ],
    comparisonTables: [{
      id: "hollywood-treatment-options",
      afterSectionId: "included-treatments",
      title: { en: "What a Hollywood Smile May Include", ar: "ما الذي قد تتضمنه ابتسامة هوليود؟" },
      columns: { en: ["Treatment", "Best for", "Main caution"], ar: ["العلاج", "مناسب لـ", "الملاحظة الأهم"] },
      rows: [
        { cells: { en: ["Veneers", "Healthy teeth needing shape, shade, or symmetry changes", "Needs careful preparation and shade planning"], ar: ["الفينير", "أسنان سليمة تحتاج تحسين الشكل أو اللون أو التناسق", "يحتاج تحضيراً محافظاً وتخطيط لون دقيقاً"] } },
        { cells: { en: ["Whitening", "Natural teeth with stains but good shape", "Does not change tooth shape or old restorations"], ar: ["التبييض", "أسنان طبيعية متصبغة وشكلها جيد", "لا يغير شكل الأسنان أو لون التركيبات القديمة"] } },
        { cells: { en: ["Implants", "Missing or non-restorable teeth", "Requires bone and gum evaluation"], ar: ["الزراعة", "أسنان مفقودة أو غير قابلة للترميم", "تحتاج تقييماً للعظم واللثة"] } },
        { cells: { en: ["Gum contouring", "Uneven or gummy smile lines", "Must respect gum health and tooth proportions"], ar: ["تعديل اللثة", "خط لثة غير منتظم أو ابتسامة لثوية", "يجب احترام صحة اللثة ونسب الأسنان"] } }
      ]
    }],
    introduction: {
      en: ["Patients choose Hollywood Smile in Jordan when they want a brighter, more confident smile—but the real goal is a result that looks natural, not bulky, artificial, or overdone.", "The most important point is this: a Hollywood Smile is a plan, not a single product. The right plan depends on your teeth, gums, bite, face shape, smile width, and expectations."],
      ar: ["عندما يفكر المرضى بابتسامة هوليود في الأردن، فهم غالباً يريدون ابتسامة أكثر إشراقاً وثقة، لكن الأهم أن تبدو طبيعية لا سميكة أو مصطنعة أو مبالغاً فيها.", "الأهم أن ابتسامة هوليود ليست منتجاً واحداً، بل خطة. الخطة الصحيحة تعتمد على الأسنان، اللثة، العضة، شكل الوجه، عرض الابتسامة، وتوقعاتك." ]
    },
    sections: [
      { id: "what-is", heading: { en: "What Is a Hollywood Smile?", ar: "ما هي ابتسامة هوليود؟" }, body: { en: ["A Hollywood Smile is a customized smile design process that improves color, shape, tooth length, spacing, gum balance, and smile harmony. The goal is not simply very white teeth; it is a smile that looks confident in photos and natural in daily conversation.", "A premium plan begins with diagnosis. Photos, facial analysis, bite review, gum health, existing fillings, and patient goals help the doctor decide what should be improved and what should be left untouched."], ar: ["ابتسامة هوليود هي عملية تصميم ابتسامة مخصصة لتحسين اللون، الشكل، طول الأسنان، الفراغات، توازن اللثة، وتناسق الابتسامة. الهدف ليس بياضاً شديداً فقط، بل ابتسامة واثقة في الصور وطبيعية أثناء الحديث.", "تبدأ الخطة الراقية بالتشخيص. الصور، تحليل الوجه، تقييم العضة، صحة اللثة، الحشوات القديمة، وهدف المريض تساعد الطبيب على تحديد ما يحتاج التحسين وما الأفضل الحفاظ عليه."] }, subsections: [{ heading: { en: "Is Hollywood Smile the same as veneers?", ar: "هل ابتسامة هوليود هي نفسها الفينير؟" }, body: { en: ["No. Veneers are one treatment. Hollywood Smile is the wider design plan. Some patients need veneers only, while others need whitening, crowns, implants, gum contouring, orthodontics, or staged treatment before the final smile is completed."], ar: ["لا. الفينير علاج واحد، أما ابتسامة هوليود فهي الخطة الأشمل لتصميم الابتسامة. بعض المرضى يحتاجون فينير فقط، وآخرون يحتاجون تبييضاً أو تيجاناً أو زراعة أو تعديل لثة أو تقويماً أو مراحل قبل الوصول للنتيجة النهائية."] } }] },
      { id: "candidate", heading: { en: "Who Is a Good Candidate?", ar: "من هو المرشح المناسب؟" }, body: { en: ["A good candidate may have stained teeth, uneven sizes, worn edges, small gaps, old cosmetic work, missing teeth, or a smile that feels narrow or tired. Healthy gums and realistic expectations are important.", "If there is active decay, gum inflammation, severe grinding, unstable bite, or very weak teeth, the first step may be stabilization rather than immediate veneers. This is not a delay; it protects the final result."], ar: ["قد يكون المرشح المناسب لديه تصبغات، اختلاف في أحجام الأسنان، حواف متآكلة، فراغات صغيرة، أعمال تجميلية قديمة، أسنان مفقودة، أو ابتسامة تبدو ضيقة أو متعبة. صحة اللثة والتوقعات الواقعية مهمتان جداً.", "إذا وُجد تسوس نشط، التهاب لثة، صرير شديد، عضة غير مستقرة، أو أسنان ضعيفة جداً، فقد تكون الخطوة الأولى هي العلاج التحضيري وليس الفينير مباشرة. هذا يحمي النتيجة النهائية."] } },
      { id: "included-treatments", heading: { en: "What Treatments Can Be Included?", ar: "ما العلاجات التي قد تدخل في الخطة؟" }, body: { en: ["Hollywood Smile veneers are common, but they are not the only answer. Whitening can refresh natural teeth before shade selection. Crowns may be needed for teeth with large restorations. Dental implants can replace missing teeth. Gum contouring can improve smile framing. Orthodontics may align teeth before conservative cosmetic work.", "The safest plan uses the least treatment needed to reach the desired result. A doctor-led consultation helps avoid unnecessary drilling, over-treatment, or a smile that looks disconnected from the face."], ar: ["فينير هوليود سمايل شائع، لكنه ليس الحل الوحيد. التبييض قد ينعش الأسنان الطبيعية قبل اختيار اللون. التيجان قد تناسب الأسنان ذات التركيبات الكبيرة. الزراعة تعوض الأسنان المفقودة. تعديل اللثة يحسن إطار الابتسامة. والتقويم قد يرتب الأسنان قبل عمل تجميلي محافظ.", "الخطة الأفضل تستخدم أقل تدخل مناسب للوصول للنتيجة المطلوبة. الاستشارة بإشراف الطبيب تساعد على تجنب البرد غير الضروري، المبالغة في العلاج، أو ابتسامة لا تناسب الوجه."] } },
      { id: "natural-design", heading: { en: "How the Doctor Designs a Natural-Looking Smile", ar: "كيف يصمم الطبيب ابتسامة طبيعية؟" }, body: { en: ["A natural Hollywood Smile is designed around the face. Tooth length, edge position, gum line, smile curve, skin tone, lip support, and tooth texture are considered together. The most elegant results often have controlled brightness, subtle translucency, and individual character.", "Patients who fear fake-looking teeth should ask about mockups, shade communication, surface texture, and before-and-after cases that resemble their starting point. Natural does not mean dull; it means believable."], ar: ["تُصمم ابتسامة هوليود الطبيعية حول الوجه. يتم النظر إلى طول الأسنان، موضع الحواف، خط اللثة، منحنى الابتسامة، لون البشرة، دعم الشفاه، وملمس الأسنان معاً. النتائج الأرقى غالباً فيها إشراقة مدروسة، شفافية ناعمة، وطابع خاص.", "من يخافون من المظهر الصناعي يمكنهم السؤال عن المعاينة، التواصل حول اللون، ملمس السطح، وحالات قبل وبعد تشبه حالتهم. الطبيعي لا يعني باهتاً، بل يعني مقنعاً ومناسباً."] } },
      { id: "cost-timeline", heading: { en: "Cost Factors in Jordan and Timeline for Local or GCC Patients", ar: "عوامل السعر في الأردن والمدة للمرضى المحليين والخليجيين" }, body: { en: ["Hollywood Smile cost in Jordan searches often ask for one number, but a responsible estimate depends on the diagnosis and smile plan. At the clinic, veneers usually range from 100 to 160 JD per tooth depending on the material, quality level, number of teeth, and case requirements. Available options may include Turkish, Korean, Spanish, German, and Swiss veneers, with the suitable choice recommended after reviewing the patient’s teeth, smile goals, desired shade, and natural result expectations.", "The total cost of a Hollywood Smile is not priced as one fixed package because each smile is different. Some patients may need 8 veneers, while others may need 10, 12, 16, or more depending on smile width, bite, tooth visibility, gum balance, and the final aesthetic plan. Additional treatments such as whitening, gum contouring, crowns, implants, replacement of old restorations, bite protection, or staged visits can also affect the final estimate. Local patients in Amman can usually plan visits with more flexibility, while GCC and international patients can start with WhatsApp photos, medical history, smile goals, and travel dates so the clinic can advise whether the case may fit a focused trip or needs staged visits, and provide an initial expected range before visiting Amman."], ar: ["عند البحث عن تكلفة ابتسامة هوليوود في الأردن أو سعر ابتسامة هوليود في الأردن يرغب المريض غالباً برقم واحد، لكن التقدير المسؤول يعتمد على التشخيص وخطة الابتسامة. تتراوح أسعار الفينير في العيادة عادة بين 100 و160 دينار أردني للسن الواحد، حسب نوع المادة، مستوى الجودة، عدد الأسنان، خطة تصميم الابتسامة، وحالة اللثة والعضة. قد تشمل الخيارات المتوفرة خامات تركية، كورية، إسبانية، ألمانية، وسويسرية، ويتم اختيار الخيار الأنسب بعد تقييم حالة الأسنان، شكل الابتسامة، درجة اللون المطلوبة، والنتيجة الطبيعية التي يرغب بها المريض.", "تكلفة ابتسامة هوليود لا تُحدد كباقة ثابتة واحدة لأن كل ابتسامة تختلف عن الأخرى. قد يحتاج بعض المرضى إلى 8 فينير، بينما قد يحتاج آخرون إلى 10 أو 12 أو 16 سناً أو أكثر حسب عرض الابتسامة، العضة، الأسنان الظاهرة عند الابتسام، توازن اللثة، والخطة الجمالية النهائية. كما قد تؤثر علاجات إضافية مثل التبييض، تعديل اللثة، التيجان، الزراعة، استبدال التركيبات القديمة، حماية العضة، أو الزيارات المرحلية على التقدير النهائي. المرضى داخل عمّان يستطيعون ترتيب الزيارات بمرونة أكبر، أما مرضى الخليج والخارج فيمكنهم البدء بصور عبر واتساب مع التاريخ الطبي وهدف الابتسامة وتواريخ السفر للحصول على نطاق مبدئي متوقع قبل زيارة عمّان."] } },
      { id: "mistakes", heading: { en: "Common Mistakes to Avoid", ar: "أخطاء شائعة يجب تجنبها" }, body: { en: ["Avoid choosing a Hollywood Smile only by the lowest package price, copying a celebrity smile, selecting the whitest shade without facial analysis, or treating every tooth the same way. These choices often create bulky or artificial results.", "Also avoid rushing treatment before gum inflammation, decay, bite problems, or old restorations are reviewed. A beautiful smile should still be comfortable, cleanable, and stable."], ar: ["تجنب اختيار هوليود سمايل بناء على أقل سعر فقط، أو نسخ ابتسامة مشهورة، أو اختيار أشد درجة بياض دون تحليل الوجه، أو علاج كل الأسنان بالطريقة نفسها. هذه القرارات قد تؤدي لنتيجة سميكة أو صناعية.", "تجنب أيضاً الاستعجال قبل فحص التهاب اللثة، التسوس، مشاكل العضة، أو التركيبات القديمة. الابتسامة الجميلة يجب أن تكون مريحة، قابلة للتنظيف، وثابتة."] } }
    ],
    faqs: [
      { question: { en: "How much does a Hollywood Smile cost in Jordan?", ar: "كم سعر ابتسامة هوليود في الأردن؟" }, answer: { en: "Hollywood Smile cost in Jordan depends mainly on the number of veneers or treatments needed. Veneers usually range from 100 to 160 JD per tooth, with the final cost affected by material, number of teeth, bite and gum condition, and whether whitening, crowns, implants, gum contouring, or other treatments are included. Patients can send photos on WhatsApp for an initial guidance range before visiting Amman.", ar: "تعتمد تكلفة ابتسامة هوليوود في الأردن بشكل أساسي على عدد الفينير أو العلاجات المطلوبة. تتراوح أسعار الفينير في العيادة عادة بين 100 و160 دينار أردني للسن الواحد، ويتأثر السعر النهائي بنوع المادة، عدد الأسنان، حالة العضة واللثة، وهل تشمل الخطة التبييض أو التيجان أو الزراعة أو تعديل اللثة أو علاجات أخرى. يمكن للمريض إرسال الصور عبر واتساب للحصول على نطاق إرشادي مبدئي قبل زيارة عمّان." } },
      { question: { en: "Can a Hollywood Smile look natural?", ar: "هل يمكن أن تبدو ابتسامة هوليود طبيعية؟" }, answer: { en: "Yes. Natural results depend on facial harmony, tooth texture, edge design, translucency, and a shade that suits the patient rather than extreme whiteness.", ar: "نعم. تعتمد النتيجة الطبيعية على تناسق الوجه، ملمس الأسنان، تصميم الحواف، الشفافية، ولون يناسب المريض وليس البياض المبالغ فيه." } },
      { question: { en: "How long does treatment take for GCC patients?", ar: "كم تستغرق لمرضى الخليج؟" }, answer: { en: "Timing depends on complexity. Some cosmetic cases can be organized into focused visits, while cases with implants, gum treatment, or orthodontics may need stages.", ar: "تعتمد المدة على التعقيد. بعض الحالات التجميلية يمكن ترتيبها بزيارات مركزة، أما الزراعة أو علاج اللثة أو التقويم فقد تحتاج مراحل." } },
      { question: { en: "Is tooth shaving always required?", ar: "هل برد الأسنان ضروري دائماً؟" }, answer: { en: "Not always. Preparation depends on tooth position, color, material, and desired change. Conservative planning aims to preserve healthy tooth structure where possible.", ar: "ليس دائماً. يعتمد التحضير على موضع السن، اللون، المادة، والتغيير المطلوب. التخطيط المحافظ يهدف للحفاظ على بنية السن قدر الإمكان." } },
      { question: { en: "Can implants be part of a Hollywood Smile?", ar: "هل يمكن أن تدخل الزراعة ضمن ابتسامة هوليود؟" }, answer: { en: "Yes, if teeth are missing or cannot be restored predictably. The implant crown must be planned with the final smile line and neighboring teeth.", ar: "نعم إذا كانت هناك أسنان مفقودة أو لا يمكن ترميمها بشكل موثوق. يجب تخطيط تاج الزراعة مع خط الابتسامة والأسنان المجاورة." } },
      { question: { en: "Can I start with WhatsApp photos?", ar: "هل أستطيع البدء بصور واتساب؟" }, answer: { en: "Yes. Photos help the team understand your goals and guide the next step, but final diagnosis and cost require clinical evaluation.", ar: "نعم. تساعد الصور الفريق على فهم هدفك وتوجيه الخطوة التالية، لكن التشخيص النهائي والسعر يحتاجان تقييماً سريرياً." } }
    ]
  },
  {
    slug: "veneers-in-jordan-cost-natural-results",
    relatedService: "dental-veneers-jordan",
    title: { en: "Veneers in Jordan: Cost, Benefits, Risks, and How to Avoid Fake-Looking Teeth", ar: "فينير الأسنان في الأردن: السعر، المميزات، المخاطر، وكيف تحصل على نتيجة طبيعية" },
    seoTitle: { en: "Veneers in Jordan: Cost, Risks & Natural Results", ar: "فينير الأسنان في الأردن: السعر والنتيجة الطبيعية" },
    metaDescription: { en: "Honest guide to veneers in Jordan: cost factors, natural results, tooth shaving, pain, risks, regrets, lifespan, and alternatives.", ar: "دليل صادق عن فينير الأسنان في الأردن: عوامل السعر، النتيجة الطبيعية، برد الأسنان، الألم، المخاطر، العمر والبدائل." },
    h1: { en: "Veneers in Jordan: Cost, Benefits, Risks, and How to Avoid Fake-Looking Teeth", ar: "فينير الأسنان في الأردن: السعر، المميزات، المخاطر، وكيف تحصل على نتيجة طبيعية" },
    excerpt: { en: "Considering veneers but worried about fake teeth, tooth shaving, pain, or regret? This guide explains how careful planning protects your smile.", ar: "تفكر بالفينير وتخاف من المظهر الصناعي أو برد الأسنان أو الألم أو الندم؟ هذا الدليل يوضح كيف يحمي التخطيط الدقيق ابتسامتك." },
    category: { en: "Veneers", ar: "الفينير" },
    readTime: "10 min read",
    coverImage: "/media/smile-case-images/natural-veneers-before-after-comparison-closeup.webp",
    coverAlt: { en: "Natural looking veneers in Jordan close up", ar: "فينير طبيعي في الأردن بصورة قريبة" },
    keywords: ["veneers in Jordan", "veneers in Amman", "veneers cost Jordan", "natural looking veneers", "do veneers look fake", "do veneers damage teeth", "veneers regret", "فينير الأسنان في الأردن", "هل الفينير يضر الأسنان", "هل الفينير يبرد الأسنان"],
    lastUpdated: "2026-07-06",
    author,
    quickAnswer: { en: ["Veneers can be an excellent option when natural teeth are healthy but need improvements in shape, shade, spacing, or proportions.", "Fake-looking veneers usually come from poor shade selection, bulky design, over-preparation, weak gum planning, or ignoring the bite."], ar: ["يمكن أن يكون الفينير خياراً ممتازاً عندما تكون الأسنان الطبيعية سليمة لكنها تحتاج تحسيناً في الشكل أو اللون أو الفراغات أو النسب.", "المظهر الصناعي غالباً ينتج عن اختيار لون غير مناسب، تصميم سميك، تحضير زائد، ضعف في تخطيط اللثة، أو تجاهل العضة."] },
    ctaText: {
      en: "Share your smile photos privately on WhatsApp for clear guidance on suitable options and next steps.",
      ar: "شارك صور ابتسامتك عبر واتساب بخصوصية، وسيقوم الفريق بإرشادك إلى الخيارات المناسبة والخطوة التالية."
    },
    internalLinks: [
      { href: "/services/dental-veneers-jordan", label: { en: "Dental Veneers in Jordan", ar: "فينير الأسنان في الأردن" }, description: { en: "Learn the veneer process, candidates, and FAQs.", ar: "تعرف على خطوات الفينير والمرشحين والأسئلة الشائعة." } },
      { href: "/services/teeth-whitening-amman", label: { en: "Teeth Whitening in Amman", ar: "تبييض الأسنان في عمّان" }, description: { en: "When whitening may be enough before veneers.", ar: "متى قد يكون التبييض كافياً قبل الفينير." } },
      { href: "/services/orthodontics-amman", label: { en: "Orthodontics in Amman", ar: "تقويم الأسنان في عمّان" }, description: { en: "Alignment can make veneer treatment more conservative.", ar: "قد يجعل التقويم خطة الفينير أكثر محافظة." } }
    ],
    suggestedImages: [{ fileName: "natural-looking-veneers-jordan-closeup.webp", alt: { en: "Natural looking veneers in Jordan", ar: "فينير طبيعي في الأردن" } }, { fileName: "veneers-consultation-amman-shade-selection.webp", alt: { en: "Veneer shade selection consultation in Amman", ar: "اختيار لون الفينير في استشارة بعمّان" } }],
    comparisonTables: [{ id: "veneers-alternatives", afterSectionId: "alternatives", title: { en: "Veneers vs Whitening vs Crowns", ar: "الفينير مقابل التبييض والتيجان" }, columns: { en: ["Option", "Can improve", "Best when"], ar: ["الخيار", "ما الذي يحسنه", "متى يناسب"] }, rows: [{ cells: { en: ["Veneers", "Shape, color, length, minor gaps, symmetry", "Teeth are structurally suitable and aesthetics are the goal"], ar: ["الفينير", "الشكل، اللون، الطول، الفراغات الصغيرة، التناسق", "عندما تكون الأسنان مناسبة والهدف تجميلي"] } }, { cells: { en: ["Whitening", "Natural tooth color only", "Shape is good and stains are the main concern"], ar: ["التبييض", "لون الأسنان الطبيعية فقط", "عندما يكون الشكل جيداً والمشكلة هي التصبغ"] } }, { cells: { en: ["Crowns", "Full coverage, strength, masking", "Teeth are weak, heavily filled, or structurally compromised"], ar: ["التيجان", "تغطية كاملة، قوة، إخفاء اللون", "عندما تكون الأسنان ضعيفة أو كثيرة الحشوات"] } }] }],
    introduction: { en: ["Veneers in Jordan are popular because they can create a refined smile transformation, but many patients quietly worry about the same things: Will my teeth look fake? Will they be shaved too much? Will I regret it later?", "Those concerns are valid. Veneers should be planned carefully, not sold aggressively. The right case, material, preparation, and shade make the difference between a premium natural smile and an overdone result."], ar: ["يبحث كثير من المرضى عن فينير الأسنان في الأردن لأنه يمنح تحولاً واضحاً للابتسامة، لكن القلق الحقيقي يكون غالباً: هل ستبدو أسناني صناعية؟ هل سيتم بردها كثيراً؟ هل سأندم لاحقاً؟", "هذه المخاوف منطقية. الفينير يجب أن يُخطط بعناية لا أن يُباع بسرعة. الحالة المناسبة، المادة الصحيحة، التحضير المحافظ، واختيار اللون هي الفارق بين ابتسامة طبيعية راقية ونتيجة مبالغ فيها."] },
    sections: [
      { id: "what-are-veneers", heading: { en: "What Are Dental Veneers?", ar: "ما هو فينير الأسنان؟" }, body: { en: ["Dental veneers are thin custom ceramic restorations bonded to the visible surfaces of teeth. They can improve discoloration, worn edges, small gaps, uneven shapes, and selected minor alignment concerns.", "The best veneers do not simply cover teeth. They are designed to match the face, lips, gum line, bite, and personality of the smile."], ar: ["فينير الأسنان هو قشور خزفية رقيقة ومخصصة تُثبت على السطح الظاهر للأسنان. يمكنها تحسين التصبغات، الحواف المتآكلة، الفراغات الصغيرة، اختلاف الشكل، وبعض مشاكل الاصطفاف البسيطة.", "أفضل فينير لا يغطي الأسنان فقط، بل يصمم بما يناسب الوجه، الشفاه، خط اللثة، العضة، وطابع الابتسامة."] } },
      { id: "suitable", heading: { en: "Who Are Veneers Suitable For?", ar: "لمن يناسب الفينير؟" }, body: { en: ["Veneers may suit patients with healthy teeth who want better shape, shade, size, or harmony. They can be especially useful when whitening alone cannot correct deep discoloration or when tooth shape is the main concern.", "They may not be the first choice for active decay, uncontrolled gum disease, severe crowding, heavy grinding, or teeth with large structural damage. In those cases, the safer plan may involve gum treatment, orthodontics, crowns, or staged care first."], ar: ["قد يناسب الفينير من لديهم أسنان سليمة ويرغبون بتحسين الشكل أو اللون أو الحجم أو التناسق. وهو مفيد خاصة عندما لا يكفي التبييض للتصبغ العميق أو عندما يكون الشكل هو المشكلة الأساسية.", "قد لا يكون الخيار الأول مع التسوس النشط، التهاب اللثة غير المسيطر عليه، التزاحم الشديد، الصرير القوي، أو الأسنان المتضررة بنيوياً. هنا قد تكون الخطة الأفضل علاج اللثة أو التقويم أو التيجان أو العلاج المرحلي أولاً."] } },
      { id: "cost", heading: { en: "How Much Do Veneers Cost in Jordan?", ar: "كم تكلفة الفينير في الأردن؟" }, body: { en: ["Veneers cost in Jordan searches often focus on a price per tooth, and it is helpful to give patients a realistic range. At the clinic, veneers usually range from 100 to 160 JD per tooth depending on the material, quality level, number of veneers, lab work, smile design requirements, gum condition, bite needs, and overall case complexity. Available veneer options may include Turkish, Korean, Spanish, German, and Swiss materials.", "The right choice is not only about price. It should be selected based on the patient’s natural teeth, desired shade, smile shape, facial features, bite, budget, natural translucency, and how natural the final result needs to look. A responsible estimate should explain why each tooth is included, whether whitening is needed first, and whether gum treatment, bite adjustment, or a night guard is recommended. Cheap veneers can become expensive if they look bulky, stain at the margins, feel uncomfortable, or fail early."], ar: ["يركز البحث عن تكلفة فينير الأسنان في الأردن أو سعر فينير الأسنان في الأردن غالباً على سعر السن الواحد، ومن المفيد توضيح نطاق واقعي دون تحويل العلاج إلى قائمة أسعار. تتراوح أسعار الفينير في العيادة عادة بين 100 و160 دينار أردني للسن الواحد، حسب نوع المادة، مستوى الجودة، عدد الأسنان، خطة تصميم الابتسامة، وحالة اللثة والعضة. قد تشمل الخيارات المتوفرة خامات تركية، كورية، إسبانية، ألمانية، وسويسرية، ويتم اختيار الخيار الأنسب بعد تقييم حالة الأسنان، شكل الابتسامة، درجة اللون المطلوبة، والنتيجة الطبيعية التي يرغب بها المريض.", "الاختيار الصحيح لا يعتمد على السعر فقط، بل على الأسنان الطبيعية، ملامح الوجه، العضة، الميزانية، ودرجة الشفافية المطلوبة للحصول على فينير طبيعي في الأردن. التقدير المسؤول يجب أن يشرح لماذا تم اختيار كل سن، وهل يلزم تبييض قبل الفينير، وهل تحتاج الحالة علاج لثة أو تعديل عضة أو واقياً ليلياً. الفينير الرخيص قد يصبح مكلفاً إذا بدا سميكاً، أو تلونت الحواف، أو شعر المريض بعدم الراحة، أو فشل مبكراً."] } },
      { id: "fake-looking", heading: { en: "Why Some Veneers Look Fake", ar: "لماذا يبدو بعض الفينير صناعياً؟" }, body: { en: ["Veneers often look fake when they are too white, too opaque, too long, too bulky, or identical on every tooth. Ignoring lip movement, gum line, smile width, and skin tone also creates a disconnected look.", "Natural looking veneers need proportion, texture, translucency, edge character, and a shade that fits the person. A beautiful result should still feel like your smile, only more refined."], ar: ["يبدو الفينير صناعياً عندما يكون شديد البياض، معتماً، طويلاً جداً، سميكاً، أو متطابقاً على كل الأسنان. تجاهل حركة الشفاه، خط اللثة، عرض الابتسامة، ولون البشرة يجعل النتيجة منفصلة عن الوجه.", "الفينير الطبيعي يحتاج نسباً صحيحة، ملمساً، شفافية، تفاصيل حواف، ولوناً يناسب الشخص. النتيجة الجميلة يجب أن تبقى ابتسامتك أنت لكن بشكل أرقى."] } },
      { id: "damage-pain-longevity", heading: { en: "Do Veneers Damage Teeth? Are They Painful? How Long Do They Last?", ar: "هل الفينير يضر الأسنان؟ هل هو مؤلم؟ وكم يدوم؟" }, body: { en: ["Veneers do not automatically damage teeth. Risk comes from over-preparation, poor bonding, weak diagnosis, or placing veneers on unsuitable teeth. Conservative preparation on a suitable case can preserve tooth structure.", "The procedure is usually managed with local anesthesia when needed. Temporary sensitivity can happen, especially to cold, but it should be discussed and monitored. Longevity depends on bonding, bite forces, hygiene, material, and habits such as grinding or nail biting."], ar: ["الفينير لا يضر الأسنان تلقائياً. الخطر يأتي من التحضير الزائد، ضعف اللصق، التشخيص غير الدقيق، أو وضع الفينير على أسنان غير مناسبة. التحضير المحافظ في الحالة المناسبة يحافظ على بنية السن.", "تتم الخطوات غالباً بتخدير موضعي عند الحاجة. قد تحدث حساسية مؤقتة خاصة للبرد، ويجب شرحها ومتابعتها. عمر الفينير يعتمد على اللصق، قوى العضة، العناية، المادة، وعادات مثل الصرير أو قضم الأظافر."] } },
      { id: "alternatives", heading: { en: "Veneers vs Whitening vs Crowns", ar: "الفينير مقابل التبييض والتيجان" }, body: { en: ["Whitening is best when the tooth shape is good and the main issue is color. Veneers are better when shape, edges, gaps, or deep discoloration must be corrected. Crowns are more suitable when teeth are weak, heavily restored, or need full coverage.", "A careful cosmetic dentist does not force one treatment on every smile. The right option depends on what is healthy, what is visible, and what will be stable long term."], ar: ["التبييض أفضل عندما يكون شكل الأسنان جيداً والمشكلة الأساسية هي اللون. الفينير أفضل عندما نحتاج تعديل الشكل أو الحواف أو الفراغات أو التصبغ العميق. أما التيجان فتناسب الأسنان الضعيفة أو كثيرة الترميم أو التي تحتاج تغطية كاملة.", "طبيب التجميل الحريص لا يفرض علاجاً واحداً على كل ابتسامة. الخيار الصحيح يعتمد على صحة الأسنان، ما يظهر عند الابتسامة، وما سيكون ثابتاً على المدى الطويل."] } }
    ],
    faqs: [
      { question: { en: "How much do veneers cost in Jordan?", ar: "كم تكلفة فينير الأسنان في الأردن؟" }, answer: { en: "Veneers usually range from 100 to 160 JD per tooth depending on the material, quality level, number of teeth, and smile design requirements. The final estimate is given after reviewing the teeth, gums, bite, and desired result.", ar: "تتراوح أسعار الفينير في العيادة عادة بين 100 و160 دينار أردني للسن الواحد، حسب نوع المادة، مستوى الجودة، عدد الأسنان، خطة تصميم الابتسامة، وحالة اللثة والعضة. يتم إعطاء التقدير النهائي بعد تقييم الأسنان واللثة والعضة والنتيجة التي يرغب بها المريض." } },
      { question: { en: "Do veneers look fake?", ar: "هل يبدو الفينير صناعياً؟" }, answer: { en: "They can look fake if poorly planned, but natural veneers are possible with correct shade, texture, proportion, gum planning, and conservative design.", ar: "قد يبدو صناعياً إذا كان التخطيط ضعيفاً، لكن الفينير الطبيعي ممكن مع اللون والملمس والنسب وتخطيط اللثة والتصميم المحافظ." } },
      { question: { en: "Do veneers damage teeth?", ar: "هل الفينير يضر الأسنان؟" }, answer: { en: "Well-planned veneers on suitable teeth can be conservative. Over-preparation, poor bonding, or treating unsuitable teeth increases risk.", ar: "الفينير المخطط جيداً على أسنان مناسبة قد يكون محافظاً. التحضير الزائد أو اللصق الضعيف أو علاج أسنان غير مناسبة يزيد الخطر." } },
      { question: { en: "Are veneers painful?", ar: "هل الفينير مؤلم؟" }, answer: { en: "Most patients tolerate veneer treatment well with local anesthesia when needed. Temporary sensitivity can occur and should be discussed before treatment.", ar: "غالباً يتحمل المرضى العلاج جيداً مع التخدير الموضعي عند الحاجة. قد تحدث حساسية مؤقتة ويجب مناقشتها قبل العلاج." } },
      { question: { en: "How long do veneers last?", ar: "كم يدوم الفينير؟" }, answer: { en: "They can last many years with good bonding, hygiene, bite protection when advised, and regular reviews. Longevity varies by case and habits.", ar: "يمكن أن تدوم لسنوات طويلة مع لصق جيد، عناية، حماية العضة عند الحاجة، ومراجعات منتظمة. العمر يختلف حسب الحالة والعادات." } },
      { question: { en: "What causes veneer regret?", ar: "ما أسباب الندم بعد الفينير؟" }, answer: { en: "Regret usually comes from rushed decisions, unrealistic shade choices, bulky design, unnecessary drilling, or not understanding maintenance and limitations.", ar: "ينتج الندم غالباً عن قرارات مستعجلة، اختيار لون غير واقعي، تصميم سميك، برد غير ضروري، أو عدم فهم العناية والحدود." } },
      { question: { en: "Can I get veneers if I grind my teeth?", ar: "هل أستطيع عمل فينير إذا كان لدي صرير؟" }, answer: { en: "Possibly, but grinding must be assessed. Some patients need bite management, material selection, or a night guard to protect the veneers.", ar: "قد يكون ممكناً لكن يجب تقييم الصرير. بعض المرضى يحتاجون ضبط العضة أو اختيار مادة مناسبة أو واقياً ليلياً لحماية الفينير." } }
    ]
  },
  {
    slug: "veneers-vs-hollywood-smile",
    relatedService: "dental-veneers-jordan",
    title: { en: "Veneers vs Hollywood Smile: What’s the Difference and Which One Do You Need?", ar: "الفرق بين الفينير وابتسامة هوليود: أيهما مناسب لك؟" },
    seoTitle: { en: "Veneers vs Hollywood Smile: Key Differences", ar: "الفرق بين الفينير وابتسامة هوليود" },
    metaDescription: { en: "Confused between veneers and Hollywood Smile? Learn the difference, treatment options, natural results, and what suits your case in Jordan.", ar: "محتار بين الفينير وابتسامة هوليود؟ تعرف على الفرق، الخيارات، النتيجة الطبيعية، وما يناسب حالتك في الأردن." },
    h1: { en: "Veneers vs Hollywood Smile: What’s the Difference and Which One Do You Need?", ar: "الفرق بين الفينير وابتسامة هوليود: أيهما مناسب لك؟" },
    excerpt: { en: "Veneers are a treatment. Hollywood Smile is a complete smile design plan. This guide helps you understand which direction fits your teeth, gums, bite, and goals.", ar: "الفينير علاج، أما ابتسامة هوليود فهي خطة تصميم ابتسامة كاملة. هذا الدليل يساعدك على معرفة الخيار الأنسب لأسنانك ولثتك وعضتك وهدفك." },
    category: { en: "Smile Design", ar: "تصميم الابتسامة" },
    readTime: "9 min read",
    coverImage: {
      en: "/media/veneers-vs-hollywood-smile-difference-jordan.webp",
      ar: "/media/veneers-vs-hollywood-smile-difference-jordan-arabic.webp"
    },
    coverAlt: { en: "Smile design consultation comparing veneers and Hollywood Smile", ar: "استشارة تصميم ابتسامة تقارن بين الفينير وابتسامة هوليود" },
    keywords: ["veneers vs Hollywood Smile", "Hollywood Smile vs veneers", "difference between veneers and Hollywood Smile", "veneers or Hollywood Smile", "smile design Jordan", "الفرق بين الفينير وابتسامة هوليود", "الفينير أم هوليود سمايل", "تصميم الابتسامة في الأردن"],
    lastUpdated: "2026-07-06",
    author,
    quickAnswer: { en: ["Veneers are thin restorations placed on existing teeth to improve appearance. A Hollywood Smile is the full design plan that may use veneers plus other treatments.", "Veneers alone may be enough when the teeth and gums are healthy and the concern is mainly shape, shade, or minor spacing."], ar: ["الفينير قشور رقيقة توضع على الأسنان الموجودة لتحسين مظهرها. أما ابتسامة هوليود فهي خطة تصميم كاملة قد تستخدم الفينير مع علاجات أخرى.", "قد يكفي الفينير وحده عندما تكون الأسنان واللثة سليمة والمشكلة الأساسية في الشكل أو اللون أو الفراغات البسيطة."] },
    ctaText: consultationCta,
    internalLinks: [
      { href: "/services/dental-veneers-jordan", label: { en: "Dental Veneers in Jordan", ar: "فينير الأسنان في الأردن" }, description: { en: "If veneers alone may solve your concern.", ar: "إذا كان الفينير وحده قد يعالج مشكلتك." } },
      { href: "/services/gummy-smile-treatment-jordan", label: { en: "Gummy Smile Treatment in Jordan", ar: "علاج الابتسامة اللثوية في الأردن" }, description: { en: "For smile plans involving gum balance.", ar: "لخطط الابتسامة التي تحتاج توازن اللثة." } },
      { href: "/services/orthodontics-amman", label: { en: "Orthodontics in Amman", ar: "تقويم الأسنان في عمّان" }, description: { en: "When alignment should be corrected before cosmetic work.", ar: "عندما يحتاج الاصطفاف للتصحيح قبل التجميل." } }
    ],
    suggestedImages: [{ fileName: "veneers-vs-hollywood-smile-jordan.webp", alt: { en: "Veneers vs Hollywood Smile comparison in Jordan", ar: "مقارنة الفينير وابتسامة هوليود في الأردن" } }],
    comparisonTables: [{ id: "veneers-hollywood-table", afterSectionId: "key-differences", title: { en: "Veneers vs Hollywood Smile Comparison", ar: "مقارنة بين الفينير وابتسامة هوليود" }, columns: { en: ["Question", "Veneers", "Hollywood Smile"], ar: ["السؤال", "الفينير", "ابتسامة هوليود"] }, rows: [{ cells: { en: ["What is it?", "A cosmetic restoration on existing teeth", "A full smile design plan"], ar: ["ما هو؟", "ترميم تجميلي على الأسنان الموجودة", "خطة تصميم ابتسامة كاملة"] } }, { cells: { en: ["Can it include whitening?", "Sometimes before shade selection", "Often, if natural teeth remain visible"], ar: ["هل يشمل التبييض؟", "أحياناً قبل اختيار اللون", "غالباً إذا بقيت أسنان طبيعية ظاهرة"] } }, { cells: { en: ["Can it replace missing teeth?", "No", "Yes, through implants or bridges when suitable"], ar: ["هل يعوض الأسنان المفقودة؟", "لا", "نعم عبر الزراعة أو الجسور عند الحاجة"] } }, { cells: { en: ["Best for", "Healthy teeth needing cosmetic refinement", "Mixed issues involving teeth, gums, bite, or missing teeth"], ar: ["الأفضل لـ", "أسنان سليمة تحتاج تحسيناً جمالياً", "مشاكل متعددة تشمل الأسنان أو اللثة أو العضة أو الفقد"] } }] }],
    introduction: { en: ["Many patients search for veneers vs Hollywood Smile because clinics and social media use the terms as if they mean the same thing. They do not.", "A simple way to understand it: veneers are one tool, while Hollywood Smile is the full smile design strategy. The right choice depends on your starting point, not on the name of the treatment."], ar: ["يبحث كثيرون عن الفرق بين الفينير وابتسامة هوليود لأن العيادات ووسائل التواصل تستخدم المصطلحين أحياناً وكأنهما شيء واحد. الحقيقة أنهما مختلفان.", "الفكرة ببساطة: الفينير أداة علاجية، أما ابتسامة هوليود فهي استراتيجية تصميم ابتسامة كاملة. الخيار الصحيح يعتمد على حالة البداية وليس اسم العلاج."] },
    sections: [
      { id: "simple-veneers", heading: { en: "Simple Explanation of Veneers", ar: "شرح بسيط للفينير" }, body: { en: ["Veneers are thin ceramic restorations bonded to existing teeth. They are used to improve shape, color, length, symmetry, worn edges, small gaps, and selected minor alignment concerns.", "They work best when the teeth are healthy enough to support bonding and when the main concern is cosmetic rather than structural."], ar: ["الفينير قشور خزفية رقيقة تثبت على الأسنان الموجودة. يستخدم لتحسين الشكل، اللون، الطول، التناسق، الحواف المتآكلة، الفراغات الصغيرة وبعض مشاكل الاصطفاف البسيطة.", "ينجح أكثر عندما تكون الأسنان سليمة بما يكفي للالتصاق وعندما تكون المشكلة تجميلية أكثر من كونها بنيوية."] } },
      { id: "simple-hollywood", heading: { en: "Simple Explanation of Hollywood Smile", ar: "شرح بسيط لابتسامة هوليود" }, body: { en: ["A Hollywood Smile is a complete smile design plan. It may include veneers, whitening, crowns, implants, gum contouring, orthodontics, or replacement of old dental work.", "The plan studies the teeth, gums, bite, smile width, lips, and face shape before deciding which treatments are needed."], ar: ["ابتسامة هوليود هي خطة تصميم ابتسامة كاملة. قد تشمل الفينير، التبييض، التيجان، الزراعة، تعديل اللثة، التقويم، أو استبدال الأعمال القديمة.", "تدرس الخطة الأسنان، اللثة، العضة، عرض الابتسامة، الشفاه، وشكل الوجه قبل تحديد العلاجات المطلوبة."] } },
      { id: "key-differences", heading: { en: "Key Differences Between Veneers and Hollywood Smile", ar: "الفروقات الأساسية بين الفينير وابتسامة هوليود" }, body: { en: ["The biggest difference is scope. Veneers focus on improving the visible surface of teeth. Hollywood Smile focuses on the entire smile system, including teeth that may need veneers, whitening, crowns, implants, gum changes, or alignment.", "This is why two patients can both ask for a Hollywood Smile but receive different treatment plans. One may need eight veneers. Another may need whitening, gum contouring, one implant, and veneers only on selected teeth."], ar: ["أكبر فرق هو نطاق العلاج. الفينير يركز على تحسين السطح الظاهر للأسنان، بينما ابتسامة هوليود تنظر إلى نظام الابتسامة كاملاً، بما فيه الأسنان التي قد تحتاج فينير أو تبييض أو تيجان أو زراعة أو تعديل لثة أو تقويم.", "لذلك قد يطلب مريضان ابتسامة هوليود لكن يحصل كل منهما على خطة مختلفة. أحدهما قد يحتاج ثمانية فينير، وآخر يحتاج تبييضاً وتعديل لثة وزراعة سن وفينير على أسنان محددة فقط."] } },
      { id: "when-veneers-enough", heading: { en: "When Veneers Alone May Be Enough", ar: "متى يكون الفينير وحده كافياً؟" }, body: { en: ["Veneers alone may be enough if your teeth are present, gums are healthy, bite is stable, and the concerns are mostly color, shape, size, worn edges, or small gaps.", "This approach can be more focused and conservative when no missing teeth, major gum imbalance, or bite problems need correction."], ar: ["قد يكفي الفينير وحده إذا كانت الأسنان موجودة، اللثة صحية، العضة مستقرة، والمشكلة غالباً في اللون أو الشكل أو الحجم أو الحواف المتآكلة أو الفراغات الصغيرة.", "هذه الخطة قد تكون أكثر تركيزاً ومحافظة عندما لا توجد أسنان مفقودة أو اختلال لثوي كبير أو مشاكل عضة تحتاج علاجاً."] } },
      { id: "when-full-plan", heading: { en: "When a Full Hollywood Smile Plan May Be Needed", ar: "متى تحتاج خطة ابتسامة هوليود كاملة؟" }, body: { en: ["A full plan may be needed when several problems overlap: missing teeth, old crowns, dark teeth, gummy smile, narrow smile, worn bite, crowding, or uneven gum levels.", "In these cases, simply placing veneers may hide some issues but not solve the underlying reason the smile looks unbalanced."], ar: ["قد تحتاج خطة كاملة عندما تتداخل عدة مشاكل: أسنان مفقودة، تيجان قديمة، أسنان داكنة، ابتسامة لثوية، ابتسامة ضيقة، تآكل في العضة، تزاحم، أو عدم انتظام خط اللثة.", "في هذه الحالات قد يخفي الفينير بعض المشاكل لكنه لا يعالج السبب الأساسي لعدم توازن الابتسامة."] } },
      { id: "cost-context", heading: { en: "Cost and Planning Context", ar: "السعر وسياق التخطيط" }, body: { en: ["Veneers and Hollywood Smile plans are priced differently because the scope is different. Veneers may be estimated by tooth and material, while a full smile plan may include whitening, gum work, crowns, implants, orthodontics, temporaries, and staged visits.", "The most honest estimate comes after the doctor identifies what is truly needed. This protects patients from paying for unnecessary treatment or choosing a package that does not solve the real problem."], ar: ["يختلف سعر الفينير عن خطة ابتسامة هوليود لأن نطاق العلاج مختلف. قد يُقدر الفينير حسب عدد الأسنان والمادة، بينما قد تشمل الخطة الكاملة التبييض، علاج اللثة، التيجان، الزراعة، التقويم، المؤقتات، والزيارات المرحلية.", "التقدير الأكثر صدقاً يأتي بعد أن يحدد الطبيب ما تحتاجه الحالة فعلاً. هذا يحمي المريض من علاج غير ضروري أو باقة لا تعالج المشكلة الحقيقية."] } },
      { id: "natural-gcc", heading: { en: "Which Is More Natural, and What Is Better for GCC Patients?", ar: "أيهما يعطي نتيجة طبيعية أكثر وما الأنسب لمرضى الخليج؟" }, body: { en: ["Neither option is automatically more natural. Natural results come from correct diagnosis, conservative preparation, shade control, gum balance, and matching the design to the face.", "For GCC patients visiting Jordan, the best option is the one that fits the travel schedule safely. Veneers-only cases may be easier to organize in a focused visit, while full Hollywood Smile plans involving implants, orthodontics, or gum treatment may require staged planning."], ar: ["لا يوجد خيار طبيعي تلقائياً أكثر من الآخر. النتيجة الطبيعية تأتي من التشخيص الصحيح، التحضير المحافظ، ضبط اللون، توازن اللثة، وتصميم يناسب الوجه.", "لمرضى الخليج القادمين إلى الأردن، الخيار الأفضل هو ما يناسب جدول السفر بأمان. حالات الفينير فقط قد تكون أسهل في زيارة مركزة، بينما خطط ابتسامة هوليود التي تشمل زراعة أو تقويم أو علاج لثة قد تحتاج مراحل."] } }
    ],
    faqs: [
      { question: { en: "Is Hollywood Smile just veneers?", ar: "هل ابتسامة هوليود هي الفينير فقط؟" }, answer: { en: "No. Veneers may be part of Hollywood Smile, but the full plan can also include whitening, crowns, implants, gum contouring, orthodontics, or other steps.", ar: "لا. قد يكون الفينير جزءاً من ابتسامة هوليود، لكن الخطة الكاملة قد تشمل التبييض أو التيجان أو الزراعة أو تعديل اللثة أو التقويم أو خطوات أخرى." } },
      { question: { en: "Which is better: veneers or Hollywood Smile?", ar: "أيهما أفضل: الفينير أم ابتسامة هوليود؟" }, answer: { en: "The better option depends on your case. Veneers suit focused cosmetic changes, while Hollywood Smile suits broader smile design needs.", ar: "الخيار الأفضل يعتمد على حالتك. الفينير يناسب التغييرات التجميلية المحددة، وابتسامة هوليود تناسب احتياجات تصميم الابتسامة الأوسع." } },
      { question: { en: "Can veneers be part of smile design?", ar: "هل يمكن أن يكون الفينير جزءاً من تصميم الابتسامة؟" }, answer: { en: "Yes. Veneers are often used inside smile design when existing teeth are healthy enough and the goal is shape, shade, and harmony.", ar: "نعم. يستخدم الفينير كثيراً ضمن تصميم الابتسامة عندما تكون الأسنان مناسبة والهدف تحسين الشكل واللون والتناسق." } },
      { question: { en: "Do I need crowns instead of veneers?", ar: "هل أحتاج تيجاناً بدل الفينير؟" }, answer: { en: "Crowns may be recommended when teeth are weak, heavily filled, cracked, root-canal treated, or need full coverage. Diagnosis decides.", ar: "قد تُنصح بالتيجان إذا كانت الأسنان ضعيفة أو كثيرة الحشوات أو متشققة أو معالجة عصبياً أو تحتاج تغطية كاملة. التشخيص هو ما يحدد." } },
      { question: { en: "Can I decide from photos only?", ar: "هل يمكن تحديد الخطة من الصور فقط؟" }, answer: { en: "Photos are useful for initial guidance, but the final plan requires clinical exam, bite review, gum assessment, and sometimes imaging.", ar: "الصور مفيدة للتوجيه الأولي، لكن الخطة النهائية تحتاج فحصاً سريرياً وتقييم العضة واللثة وأحياناً التصوير." } }
    ]
  },
  {
    slug: "dental-implants-amman-cost-pain-recovery",
    relatedService: "dental-implants-amman",
    title: { en: "Dental Implants in Amman: Cost, Pain, Recovery Time, and Who Is a Candidate", ar: "زراعة الأسنان في عمان: التكلفة، الألم، مدة الشفاء، ومن هو المرشح المناسب؟" },
    seoTitle: { en: "Dental Implants in Amman: Cost, Pain & Recovery", ar: "زراعة الأسنان في عمان: التكلفة والألم والشفاء" },
    metaDescription: { en: "Guide to dental implants in Amman: cost factors, pain, recovery time, bone grafting, steps, candidates, and implant vs bridge vs denture.", ar: "دليل زراعة الأسنان في عمان: التكلفة، الألم، مدة الشفاء، ترقيع العظم، الخطوات، المرشح المناسب، والبدائل." },
    h1: { en: "Dental Implants in Amman: Cost, Pain, Recovery Time, and Who Is a Candidate", ar: "زراعة الأسنان في عمان: التكلفة، الألم، مدة الشفاء، ومن هو المرشح المناسب؟" },
    excerpt: { en: "A practical implant guide for patients in Jordan and abroad, covering cost factors, discomfort, healing, bone grafting, and treatment choices.", ar: "دليل عملي للزراعة للمرضى داخل الأردن وخارجه، يوضح عوامل التكلفة، الألم، الشفاء، ترقيع العظم، وخيارات العلاج." },
    category: { en: "Dental Implants", ar: "زراعة الأسنان" },
    readTime: "10 min read",
    coverImage: {
      en: "/media/dental-implants-amman-jordan-cost-pain-recovery.webp",
      ar: "/media/dental-implants-amman-jordan-cost-pain-recovery-arabic.webp"
    },
    coverAlt: { en: "Dental implant final crown result in Amman", ar: "نتيجة تاج زراعة الأسنان في عمّان" },
    keywords: ["dental implants in Amman", "dental implants Jordan", "dental implant cost Jordan", "dental implant pain", "dental implant recovery time", "best dental implants Amman", "زراعة الأسنان في عمان", "تكلفة زراعة الأسنان في الأردن", "هل زراعة الأسنان مؤلمة"],
    lastUpdated: "2026-07-06",
    author,
    quickAnswer: { en: ["Dental implants replace missing teeth with an artificial root placed in the jawbone and a crown or prosthetic restoration above it.", "Pain is usually managed with local anesthesia, but recovery, timing, and cost depend on bone, gums, medical health, implant number, and restoration type."], ar: ["زراعة الأسنان تعوض الأسنان المفقودة بجذر صناعي يوضع في عظم الفك ثم تاج أو تعويض فوقه.", "يُدار الألم غالباً بالتخدير الموضعي، لكن الشفاء والمدة والتكلفة تعتمد على العظم واللثة والصحة العامة وعدد الزرعات ونوع التعويض."] },
    ctaText: { en: "Share your photos or X-rays on WhatsApp for clear implant guidance and next steps.", ar: "شارك الصور أو الأشعة عبر واتساب للحصول على توجيه واضح حول الزراعة والخطوة التالية." },
    internalLinks: [
      { href: "/services/dental-implants-amman", label: { en: "Dental Implants in Amman", ar: "زراعة الأسنان في عمّان" }, description: { en: "Implant assessment, process, benefits, and FAQs.", ar: "تقييم الزراعة، الخطوات، المزايا، والأسئلة." } },
      { href: "/services/dental-veneers-jordan", label: { en: "Dental Veneers in Jordan", ar: "فينير الأسنان في الأردن" }, description: { en: "For aesthetic improvement of existing teeth.", ar: "لتحسين جمال الأسنان الموجودة." } },
      { href: "/contact", label: { en: "Book Your Consultation", ar: "احجز استشارتك" }, description: { en: "Start with photos, X-rays, and treatment goals.", ar: "ابدأ بالصور والأشعة وهدف العلاج." } }
    ],
    suggestedImages: [{ fileName: "dental-implants-amman-final-crown.webp", alt: { en: "Dental implants in Amman final crown", ar: "تاج زراعة الأسنان النهائي في عمّان" } }, { fileName: "dental-implant-xray-jordan-planning.webp", alt: { en: "Dental implant X-ray planning in Jordan", ar: "تخطيط زراعة الأسنان بالأشعة في الأردن" } }],
    comparisonTables: [{ id: "implant-alternatives", afterSectionId: "alternatives", title: { en: "Dental Implant vs Bridge vs Denture", ar: "الزراعة مقابل الجسر والطقم" }, columns: { en: ["Option", "May suit", "Important note"], ar: ["الخيار", "قد يناسب", "ملاحظة مهمة"] }, rows: [{ cells: { en: ["Implant", "Missing tooth with suitable bone and gum support", "Needs surgical planning and healing time"], ar: ["الزراعة", "سن مفقود مع عظم ولثة مناسبين", "تحتاج تخطيطاً جراحياً ووقت شفاء"] } }, { cells: { en: ["Bridge", "Missing tooth with neighboring teeth needing crowns", "May involve preparing adjacent teeth"], ar: ["الجسر", "سن مفقود مع أسنان مجاورة تحتاج تيجاناً", "قد يتطلب تحضير الأسنان المجاورة"] } }, { cells: { en: ["Denture", "Multiple missing teeth or temporary replacement", "May be removable and less stable"], ar: ["الطقم", "فقدان عدة أسنان أو تعويض مؤقت", "قد يكون متحركاً وأقل ثباتاً"] } }] }],
    introduction: { en: ["Dental implants in Amman are a strong option for replacing missing teeth, but patients usually want honest answers before booking: How much will it cost? Will it hurt? How long is recovery? Am I even a candidate?", "The answer depends on diagnosis. A responsible implant plan begins with imaging, bone and gum evaluation, medical history, bite assessment, and a clear restoration goal."], ar: ["تُعد زراعة الأسنان في عمان خياراً قوياً لتعويض الأسنان المفقودة، لكن المرضى يريدون إجابات واضحة قبل الحجز: كم التكلفة؟ هل هي مؤلمة؟ كم مدة الشفاء؟ وهل أنا مرشح مناسب؟", "الإجابة تعتمد على التشخيص. تبدأ الخطة المسؤولة بالتصوير، تقييم العظم واللثة، التاريخ الطبي، العضة، والهدف النهائي للتعويض."] },
    sections: [
      { id: "what-is-implant", heading: { en: "What Is a Dental Implant?", ar: "ما هي زراعة الأسنان؟" }, body: { en: ["A dental implant is an artificial tooth root placed in the jawbone to support a crown, bridge, or larger prosthetic solution. It is designed to restore function and appearance when a tooth is missing or cannot be saved predictably.", "The visible tooth is usually the crown, not the implant itself. For aesthetic areas, gum contour, crown shape, shade, and neighboring teeth matter as much as implant position."], ar: ["زراعة الأسنان هي جذر صناعي يوضع داخل عظم الفك لدعم تاج أو جسر أو تعويض أكبر. هدفها استعادة الوظيفة والمظهر عندما يكون السن مفقوداً أو غير قابل للحفاظ عليه بشكل موثوق.", "الجزء الظاهر عادة هو التاج وليس الزرعة نفسها. في المناطق الجمالية، خط اللثة وشكل التاج واللون والأسنان المجاورة مهمة بقدر موضع الزرعة."] } },
      { id: "candidates", heading: { en: "Who Needs Dental Implants?", ar: "من يحتاج زراعة الأسنان؟" }, body: { en: ["Implants may suit patients missing one tooth, several teeth, or teeth that are badly damaged and cannot be restored. They can also help patients who struggle with unstable removable dentures.", "Good candidates usually have suitable bone, healthy gums, controlled medical conditions, and realistic expectations. Smoking, uncontrolled diabetes, active gum disease, or insufficient bone may require extra planning or treatment first."], ar: ["قد تناسب الزراعة من فقدوا سناً أو عدة أسنان، أو لديهم أسنان متضررة بشدة لا يمكن ترميمها. وقد تساعد أيضاً من يعانون من أطقم متحركة غير ثابتة.", "المرشح الجيد غالباً لديه عظم مناسب، لثة صحية، حالات طبية مسيطر عليها، وتوقعات واقعية. التدخين، السكري غير المسيطر عليه، أمراض اللثة النشطة، أو نقص العظم قد تحتاج تخطيطاً أو علاجاً إضافياً أولاً."] } },
      { id: "process", heading: { en: "Dental Implant Process Step by Step", ar: "خطوات زراعة الأسنان" }, body: { en: ["The process usually begins with consultation, imaging, medical review, and treatment planning. Then implant placement is performed when the site is suitable. Healing time allows the implant to integrate with bone before the final crown or prosthetic is completed.", "Some cases can be restored in a simpler sequence, while others require extraction, bone grafting, temporary teeth, gum shaping, or staged visits. The plan should be explained before treatment begins."], ar: ["تبدأ العملية غالباً بالاستشارة، التصوير، مراجعة الحالة الطبية، وخطة العلاج. بعد ذلك توضع الزرعة عندما يكون الموقع مناسباً. يحتاج العظم وقتاً للالتئام قبل تركيب التاج أو التعويض النهائي.", "بعض الحالات تتم بتسلسل أبسط، وأخرى تحتاج خلعاً أو ترقيع عظم أو أسناناً مؤقتة أو تشكيل لثة أو زيارات مرحلية. يجب شرح الخطة قبل البدء."] } },
      { id: "pain-recovery", heading: { en: "Does Dental Implant Treatment Hurt? How Long Does Recovery Take?", ar: "هل زراعة الأسنان مؤلمة؟ وكم مدة الشفاء؟" }, body: { en: ["Implant placement is typically performed with local anesthesia, so the procedure itself should be controlled. After treatment, soreness, swelling, or pressure can occur for a few days depending on the case and whether additional procedures were done.", "Recovery time varies. Soft tissue may settle relatively quickly, while bone integration takes longer and depends on bone quality, implant site, grafting, general health, and follow-up. Patients should receive clear aftercare instructions and realistic timing."], ar: ["تتم الزراعة غالباً بتخدير موضعي، لذلك يفترض أن تكون الجلسة مسيطراً عليها. بعد العلاج قد يحدث انزعاج أو تورم أو ضغط لعدة أيام حسب الحالة وهل تم إجراء خطوات إضافية.", "مدة الشفاء تختلف. قد تهدأ الأنسجة اللينة بسرعة نسبية، بينما يحتاج التحام العظم وقتاً أطول ويتأثر بجودة العظم ومكان الزرعة والترقيع والصحة العامة والمتابعة. يجب أن يحصل المريض على تعليمات واضحة وتوقيت واقعي."] } },
      { id: "cost-bone", heading: { en: "What Affects Implant Cost in Amman? Do You Need Bone Grafting?", ar: "ما الذي يؤثر على تكلفة الزراعة في عمان؟ وهل تحتاج ترقيع عظم؟" }, body: { en: ["Dental implant cost Jordan varies by imaging, implant system, number of implants, bone or gum needs, surgical complexity, temporary teeth, crown material, lab work, and visit sequence. A single advertised price may not include everything needed for a stable result.", "Bone grafting may be needed when the jawbone is too thin, short, or damaged after tooth loss or infection. Not every patient needs grafting, but it can be important for implant stability, gum contour, and the final crown position."], ar: ["تختلف تكلفة زراعة الأسنان في الأردن حسب التصوير، نظام الزرعة، عدد الزرعات، حاجة العظم أو اللثة، صعوبة الجراحة، الأسنان المؤقتة، مادة التاج، المختبر، وتسلسل الزيارات. السعر المعلن الواحد قد لا يشمل كل ما تحتاجه النتيجة المستقرة.", "قد تحتاج الحالة إلى ترقيع عظم عندما يكون العظم رقيقاً أو قصيراً أو متضرراً بعد فقد السن أو الالتهاب. ليس كل مريض يحتاج ترقيعاً، لكنه قد يكون مهماً لثبات الزرعة وشكل اللثة وموضع التاج النهائي."] } },
      { id: "alternatives", heading: { en: "Dental Implant vs Bridge vs Denture", ar: "زراعة الأسنان مقابل الجسر والطقم" }, body: { en: ["An implant replaces the missing root and supports a crown without depending on neighboring teeth when the case is suitable. A bridge can be useful if adjacent teeth already need crowns. A denture may be used temporarily or when multiple teeth need replacement and fixed options are not suitable.", "The right option depends on bone, gums, budget, time, neighboring teeth, medical factors, and the final smile plan."], ar: ["تعوض الزراعة الجذر المفقود وتدعم تاجاً دون الاعتماد على الأسنان المجاورة عندما تكون الحالة مناسبة. الجسر قد يكون مفيداً إذا كانت الأسنان المجاورة تحتاج تيجاناً أصلاً. والطقم قد يستخدم مؤقتاً أو عندما تكون الأسنان المفقودة متعددة ولا تناسب الخيارات الثابتة.", "الخيار الصحيح يعتمد على العظم، اللثة، الميزانية، الوقت، الأسنان المجاورة، العوامل الطبية، وخطة الابتسامة النهائية."] } }
    ],
    faqs: [
      { question: { en: "How much do dental implants cost in Amman?", ar: "كم تكلفة زراعة الأسنان في عمان؟" }, answer: { en: "Cost depends on imaging, implant system, number of implants, bone grafting, gum condition, crown material, temporary teeth, and visit sequence.", ar: "تعتمد التكلفة على التصوير، نوع الزرعة، عدد الزرعات، ترقيع العظم، حالة اللثة، مادة التاج، الأسنان المؤقتة، وتسلسل الزيارات." } },
      { question: { en: "Is dental implant treatment painful?", ar: "هل زراعة الأسنان مؤلمة؟" }, answer: { en: "The procedure is usually performed with local anesthesia. Some soreness or swelling can occur after treatment and varies by complexity.", ar: "تتم غالباً بتخدير موضعي. قد يحدث انزعاج أو تورم بعد العلاج ويختلف حسب صعوبة الحالة." } },
      { question: { en: "How long does implant recovery take?", ar: "كم مدة الشفاء بعد الزراعة؟" }, answer: { en: "Soft tissue recovery can be shorter, while bone integration takes longer. Timing depends on bone quality, grafting, health, and implant location.", ar: "قد يكون شفاء الأنسجة اللينة أقصر، بينما يحتاج التحام العظم وقتاً أطول. تعتمد المدة على جودة العظم والترقيع والصحة ومكان الزرعة." } },
      { question: { en: "Do I need a bone graft?", ar: "هل أحتاج ترقيع عظم؟" }, answer: { en: "Only if bone volume or shape is insufficient for stable placement. Imaging and examination are needed to decide.", ar: "فقط إذا كان حجم أو شكل العظم غير كافٍ لوضع زرعة ثابتة. يلزم التصوير والفحص للتحديد." } },
      { question: { en: "Can implants be done for front teeth?", ar: "هل يمكن زراعة الأسنان الأمامية؟" }, answer: { en: "Yes, but front teeth require careful aesthetic planning for gum contour, crown shape, shade, and timing.", ar: "نعم، لكن الأسنان الأمامية تحتاج تخطيطاً جمالياً دقيقاً لخط اللثة وشكل التاج واللون والتوقيت." } },
      { question: { en: "Can international patients plan implants in Jordan?", ar: "هل يستطيع المرضى من الخارج التخطيط للزراعة في الأردن؟" }, answer: { en: "Yes. Start with photos, X-rays if available, medical history, and travel dates. Some cases require staged visits.", ar: "نعم. ابدأ بالصور والأشعة إن وجدت والتاريخ الطبي وتواريخ السفر. بعض الحالات تحتاج زيارات مرحلية." } }
    ]
  },
  {
    slug: "veneers-vs-dental-implants",
    relatedService: "dental-veneers-jordan",
    title: { en: "Veneers vs Dental Implants: Which Smile Treatment Is Right for You?", ar: "الفينير أم زراعة الأسنان: أي علاج مناسب لابتسامتك؟" },
    seoTitle: { en: "Veneers vs Dental Implants: Which Is Right?", ar: "الفينير أم زراعة الأسنان: أيهما مناسب؟" },
    metaDescription: { en: "Veneers vs dental implants explained: when to improve existing teeth, when to replace missing teeth, and when a smile makeover needs both.", ar: "الفرق بين الفينير والزراعة: متى نحسن الأسنان الموجودة، ومتى نعوض الأسنان المفقودة، ومتى تحتاج الخطة الاثنين معاً." },
    h1: { en: "Veneers vs Dental Implants: Which Smile Treatment Is Right for You?", ar: "الفينير أم زراعة الأسنان: أي علاج مناسب لابتسامتك؟" },
    excerpt: { en: "A decision-making guide for patients who want a better smile but are unsure whether they need veneers, implants, crowns, whitening, orthodontics, or a combined plan.", ar: "دليل قرار لمن يريدون تحسين الابتسامة ولا يعرفون هل يحتاجون فينير أو زراعة أو تيجان أو تبييض أو تقويم أو خطة مشتركة." },
    category: { en: "Treatment Guide", ar: "دليل العلاج" },
    readTime: "9 min read",
    coverImage: {
      en: "/media/veneers-vs-dental-implants-smile-treatment-jordan.webp",
      ar: "/media/veneers-vs-dental-implants-smile-treatment-jordan-arabic.webp"
    },
    coverAlt: { en: "Planning veneers and dental implants for smile makeover in Jordan", ar: "تخطيط الفينير وزراعة الأسنان لتحسين الابتسامة في الأردن" },
    keywords: ["veneers vs dental implants", "veneers or implants", "dental implants vs veneers", "missing tooth veneers or implant", "smile makeover Jordan", "الفينير أم زراعة الأسنان", "الفرق بين الفينير وزراعة الأسنان", "زراعة الأسنان أم الفينير", "علاج الابتسامة في الأردن"],
    lastUpdated: "2026-07-06",
    author,
    quickAnswer: { en: ["Veneers improve existing teeth. Dental implants replace missing teeth or teeth that cannot be saved predictably.", "Some smile makeover cases need both: implants to restore missing teeth and veneers to refine the visible natural teeth."], ar: ["الفينير يحسن الأسنان الموجودة. زراعة الأسنان تعوض الأسنان المفقودة أو التي لا يمكن الحفاظ عليها بشكل موثوق.", "بعض حالات تجميل الابتسامة تحتاج الاثنين: زراعة لتعويض الأسنان المفقودة وفينير لتحسين الأسنان الطبيعية الظاهرة."] },
    ctaText: consultationCta,
    internalLinks: [
      { href: "/services/dental-veneers-jordan", label: { en: "Dental Veneers in Jordan", ar: "فينير الأسنان في الأردن" }, description: { en: "For improving existing healthy teeth.", ar: "لتحسين الأسنان السليمة الموجودة." } },
      { href: "/services/dental-implants-amman", label: { en: "Dental Implants in Amman", ar: "زراعة الأسنان في عمّان" }, description: { en: "For replacing missing or non-restorable teeth.", ar: "لتعويض الأسنان المفقودة أو غير القابلة للترميم." } },
      { href: "/services/teeth-whitening-amman", label: { en: "Teeth Whitening in Amman", ar: "تبييض الأسنان في عمّان" }, description: { en: "For natural teeth when color is the main concern.", ar: "للأسنان الطبيعية عندما يكون اللون هو المشكلة الأساسية." } }
    ],
    suggestedImages: [{ fileName: "veneers-vs-dental-implants-smile-makeover-jordan.webp", alt: { en: "Veneers vs dental implants for smile makeover in Jordan", ar: "الفينير مقابل زراعة الأسنان لتجميل الابتسامة في الأردن" } }],
    comparisonTables: [{ id: "decision-table", afterSectionId: "decision-table", title: { en: "Decision Table by Patient Case", ar: "جدول القرار حسب حالة المريض" }, columns: { en: ["Your situation", "Likely direction", "Why"], ar: ["حالتك", "الاتجاه المحتمل", "السبب"] }, rows: [{ cells: { en: ["Healthy tooth but unattractive shape or color", "Veneers or whitening", "The tooth exists and can be improved aesthetically"], ar: ["سن سليم لكن شكله أو لونه غير مرضٍ", "فينير أو تبييض", "السن موجود ويمكن تحسينه جمالياً"] } }, { cells: { en: ["Tooth is missing", "Dental implant or bridge", "A missing root/tooth must be replaced"], ar: ["سن مفقود", "زراعة أو جسر", "يجب تعويض الجذر أو السن المفقود"] } }, { cells: { en: ["Tooth is badly broken or weak", "Crown, implant, or staged plan", "Diagnosis decides whether the tooth can be saved"], ar: ["سن مكسور أو ضعيف جداً", "تاج أو زراعة أو خطة مرحلية", "التشخيص يحدد هل يمكن إنقاذ السن"] } }, { cells: { en: ["Missing teeth plus worn front teeth", "Combined smile makeover", "Implants restore gaps; veneers refine visible teeth"], ar: ["أسنان مفقودة مع تآكل بالأسنان الأمامية", "خطة ابتسامة مشتركة", "الزراعة تعوض الفقد والفينير يحسن الأسنان الظاهرة"] } }] }],
    introduction: { en: ["Patients often compare veneers vs dental implants when they know they want a better smile but are not sure what treatment actually solves the problem.", "The key difference is simple: veneers improve teeth that are already there; dental implants replace teeth that are missing or cannot be saved. In a real smile makeover, the answer may be one, the other, or both."], ar: ["يقارن المرضى كثيراً بين الفينير وزراعة الأسنان عندما يعرفون أنهم يريدون ابتسامة أفضل لكنهم لا يعرفون ما العلاج الذي يحل المشكلة فعلاً.", "الفرق الأساسي بسيط: الفينير يحسن الأسنان الموجودة، والزراعة تعوض الأسنان المفقودة أو غير القابلة للحفاظ عليها. في تجميل الابتسامة الحقيقي قد تحتاج أحدهما أو الاثنين معاً."] },
    sections: [
      { id: "veneers-fix", heading: { en: "What Veneers Can Fix", ar: "ما الذي يعالجه الفينير؟" }, body: { en: ["Veneers can improve the appearance of existing teeth. They may correct discoloration, uneven shape, worn edges, small gaps, mild rotations, and tooth proportions.", "They are not used to replace a missing tooth root. If the tooth is absent, severely loose, or structurally hopeless, a veneer cannot solve that problem."], ar: ["يحسن الفينير مظهر الأسنان الموجودة. قد يعالج التصبغ، اختلاف الشكل، الحواف المتآكلة، الفراغات الصغيرة، الدوران البسيط، ونسب الأسنان.", "لكنه لا يعوض جذر سن مفقود. إذا كان السن غير موجود أو متحركاً بشدة أو غير قابل للترميم، فلن يحل الفينير المشكلة."] } },
      { id: "implants-fix", heading: { en: "What Dental Implants Can Fix", ar: "ما الذي تعالجه زراعة الأسنان؟" }, body: { en: ["Dental implants replace missing teeth by placing an artificial root in the jawbone and restoring it with a crown or prosthetic. They can restore chewing stability and close gaps caused by missing teeth.", "Implants do not change the color or shape of neighboring healthy teeth. If the rest of the smile needs aesthetic refinement, veneers, whitening, crowns, or gum treatment may be added to the plan."], ar: ["تعوض زراعة الأسنان الأسنان المفقودة بوضع جذر صناعي في عظم الفك ثم ترميمه بتاج أو تعويض. يمكنها استعادة ثبات المضغ وإغلاق فراغات الفقد.", "الزراعة لا تغير لون أو شكل الأسنان السليمة المجاورة. إذا كانت بقية الابتسامة تحتاج تحسيناً جمالياً فقد تضاف الفينير أو التبييض أو التيجان أو علاج اللثة إلى الخطة."] } },
      { id: "main-difference", heading: { en: "The Main Difference Between Veneers and Implants", ar: "الفرق الأساسي بين الفينير والزراعة" }, body: { en: ["Veneers are cosmetic restorations on existing teeth. Implants are tooth replacement solutions. This distinction prevents a common misunderstanding: you do not choose veneers or implants based on which one is more beautiful; you choose based on whether the tooth exists and whether it can be saved.", "If a tooth is healthy but unattractive, veneers may be considered. If a tooth is missing or badly damaged, implant planning may be more appropriate."], ar: ["الفينير ترميم تجميلي على الأسنان الموجودة. الزراعة حل لتعويض الأسنان. هذا الفرق يمنع سوء فهم شائع: لا تختار بينهما بناء على أيهما أجمل، بل بناء على هل السن موجود وهل يمكن الحفاظ عليه.", "إذا كان السن سليماً لكنه غير جذاب، قد يُدرس الفينير. وإذا كان السن مفقوداً أو متضرراً بشدة، فقد تكون الزراعة أنسب."] } },
      { id: "healthy-vs-missing", heading: { en: "If Your Tooth Is Healthy but Unattractive vs Missing or Badly Damaged", ar: "إذا كان السن سليماً لكن غير جميل مقابل مفقود أو متضرر" }, body: { en: ["A healthy but unattractive tooth may need whitening, reshaping, bonding, orthodontics, or veneers depending on the concern. The goal is to preserve as much natural tooth structure as possible while improving the smile.", "A missing tooth or hopeless tooth needs a replacement strategy. This may be an implant, bridge, or removable option. The decision depends on bone, gums, neighboring teeth, budget, and timing."], ar: ["السن السليم غير المرضي جمالياً قد يحتاج تبييضاً أو إعادة تشكيل أو بوندنج أو تقويماً أو فينير حسب المشكلة. الهدف الحفاظ على أكبر قدر ممكن من بنية السن مع تحسين الابتسامة.", "أما السن المفقود أو غير القابل للحفاظ عليه فيحتاج استراتيجية تعويض. قد تكون زراعة أو جسراً أو خياراً متحركاً. القرار يعتمد على العظم واللثة والأسنان المجاورة والميزانية والوقت."] } },
      { id: "combine", heading: { en: "Can Veneers and Implants Be Combined?", ar: "هل يمكن الجمع بين الفينير والزراعة؟" }, body: { en: ["Yes. Many smile makeover cases combine treatments. For example, an implant can replace a missing side tooth while veneers improve the front teeth. The important detail is sequencing: implant position, gum healing, shade selection, and veneer design must be coordinated.", "When the plan is coordinated, the implant crown and veneers can look like one harmonious smile rather than separate dental work."], ar: ["نعم. كثير من حالات تجميل الابتسامة تجمع بين العلاجات. مثلاً قد تعوض الزراعة سناً جانبياً مفقوداً بينما يحسن الفينير الأسنان الأمامية. الأهم هو ترتيب المراحل: موضع الزرعة، شفاء اللثة، اختيار اللون، وتصميم الفينير يجب أن تكون منسقة.", "عندما تكون الخطة منسقة يمكن أن يبدو تاج الزراعة والفينير كابتسامة واحدة متناغمة وليس أعمالاً منفصلة."] } },
      { id: "cost-timing", heading: { en: "Cost and Timing Depend on the Real Diagnosis", ar: "التكلفة والمدة تعتمدان على التشخيص الحقيقي" }, body: { en: ["Veneers and implants do not have the same cost structure. Veneers depend on tooth count, material, gum condition, bite, and lab work. Implants depend on imaging, bone condition, implant number, grafting needs, crown design, and healing stages.", "A combined smile makeover may require careful sequencing so the implant crown, veneers, whitening, and gum line match. A consultation prevents choosing a treatment because of price alone instead of suitability."], ar: ["لا يتشابه الفينير والزراعة في طريقة احتساب التكلفة. الفينير يعتمد على عدد الأسنان، المادة، حالة اللثة، العضة، والمختبر. الزراعة تعتمد على التصوير، حالة العظم، عدد الزرعات، الحاجة للترقيع، تصميم التاج، ومراحل الشفاء.", "قد تحتاج خطة الابتسامة المشتركة إلى ترتيب دقيق حتى يتناسق تاج الزراعة والفينير والتبييض وخط اللثة. الاستشارة تمنع اختيار العلاج بسبب السعر فقط بدلاً من الملاءمة."] } },
      { id: "decision-table", heading: { en: "How the Doctor Chooses the Right Treatment Plan", ar: "كيف يختار الطبيب الخطة المناسبة؟" }, body: { en: ["The doctor evaluates tooth vitality, remaining structure, gum health, bone levels, bite forces, smile line, existing restorations, and the patient’s goals. Photos and imaging help separate cosmetic concerns from structural problems.", "The best plan is not always the most treatment. It is the plan that solves the real problem with the least appropriate intervention and gives the patient a result that can be maintained."], ar: ["يقيم الطبيب حيوية السن، البنية المتبقية، صحة اللثة، مستوى العظم، قوى العضة، خط الابتسامة، التركيبات القديمة، وهدف المريض. تساعد الصور والأشعة على فصل المشكلة الجمالية عن المشكلة البنيوية.", "أفضل خطة ليست دائماً الأكثر علاجاً، بل الخطة التي تحل المشكلة الحقيقية بأقل تدخل مناسب وتمنح المريض نتيجة قابلة للمحافظة عليها."] } }
    ],
    faqs: [
      { question: { en: "Can veneers replace a missing tooth?", ar: "هل يعوض الفينير سناً مفقوداً؟" }, answer: { en: "No. Veneers improve existing teeth. A missing tooth usually needs an implant, bridge, denture, or another replacement option.", ar: "لا. الفينير يحسن الأسنان الموجودة. السن المفقود يحتاج غالباً زراعة أو جسراً أو طقماً أو خيار تعويض آخر." } },
      { question: { en: "Should I get veneers or implants?", ar: "هل أحتاج فينير أم زراعة؟" }, answer: { en: "If the tooth is healthy but unattractive, veneers may help. If it is missing or cannot be saved, implant planning may be needed.", ar: "إذا كان السن سليماً لكن غير جميل، قد يساعد الفينير. وإذا كان مفقوداً أو غير قابل للحفاظ عليه، فقد تحتاج زراعة." } },
      { question: { en: "Can one smile makeover include both?", ar: "هل يمكن أن تشمل خطة الابتسامة الاثنين؟" }, answer: { en: "Yes. Implants can replace missing teeth while veneers refine existing visible teeth, as long as timing and shade are coordinated.", ar: "نعم. يمكن للزراعة تعويض الأسنان المفقودة والفينير تحسين الأسنان الظاهرة، بشرط تنسيق التوقيت واللون." } },
      { question: { en: "Which lasts longer, veneers or implants?", ar: "أيهما يدوم أكثر الفينير أم الزراعة؟" }, answer: { en: "They are different treatments. Longevity depends on planning, hygiene, bite forces, bone and gum health, material, and maintenance.", ar: "هما علاجان مختلفان. يعتمد العمر على التخطيط والعناية وقوى العضة وصحة العظم واللثة والمادة والمتابعة." } },
      { question: { en: "What if my front tooth is badly damaged?", ar: "ماذا لو كان السن الأمامي متضرراً بشدة؟" }, answer: { en: "The dentist must assess whether it can be restored with a crown or whether extraction and implant planning are safer. Photos alone are not enough.", ar: "يجب أن يقيّم الطبيب هل يمكن ترميمه بتاج أم أن الخلع والزراعة أكثر أماناً. الصور وحدها لا تكفي." } },
      { question: { en: "Can I start with WhatsApp before visiting Jordan?", ar: "هل يمكن البدء عبر واتساب قبل زيارة الأردن؟" }, answer: { en: "Yes. Send smile photos, X-rays if available, medical history, and your goals. Final decisions require clinical evaluation.", ar: "نعم. أرسل صور الابتسامة والأشعة إن وجدت والتاريخ الطبي وهدفك. القرارات النهائية تحتاج تقييماً سريرياً." } }
    ]
  }
];
